AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  WebSiteHelper:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::593007389919:role/admin_ram'
      Runtime: nodejs8.10
      Timeout: 3
